steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - artifacts/api-server/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: us-east5-docker.pkg.dev/panoptesaimod/panoptes-api/panoptes-api:latest
